### STAGE 1: Build ###

# We label our stage as ‘builder’
FROM node:11 as builder

COPY package.json yarn.lock ./

## Storing node modules on a separate layer will prevent unnecessary yarn installs at each build
RUN yarn install && mkdir /usr/src/app && mkdir /usr/src/app/logs && mv ./node_modules ./usr/src/app

WORKDIR /usr/src/app

COPY . .

## Build the node app in production mode and store the artifacts in dist folder
RUN yarn start production